name: whobrowser
version: '0.01a'
summary: Snapped Downloader+Starter for Tor Browser and i2p Browser
base: core18
description: |
  A highly experimental snapped version of Tor Browser and i2p Browser.

apps:
  update-torbrowser:
    command: desktop-launch $SNAP/usr/bin/update-torbrowser --devbuildpassthrough
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
  update-i2pbrowser:
    command: desktop-launch $SNAP/usr/bin/update-i2pbrowser --devbuildpassthrough
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
  torbrowser:
    command: desktop-launch $SNAP/usr/bin/torbrowser
    desktop: usr/share/applications/janondisttorbrowser.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa
  i2pbrowser:
    command: desktop-launch $SNAP/usr/bin/i2pbrowser
    plugs:
      - network
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - mir
      - browser-support
      - pulseaudio
      - alsa

grade: devel
confinement: strict

parts:
  whobrowser:
    after: [desktop-gtk3]
    source: https://github.com/eyedeekay/whobrowser.git
    source-subdir: "."
    plugin: make
    make-parameters:
      - DESTDIR=$(SNAP)
      - install
    stage-packages:
      - dirmgr
      - gnupg2
      - devscripts
    stage:
      - .
    prime:
      - .
